---
title: "Site-specific Data Merge"
author: "Marc Peipoch"
date: "9/16/2022"
output: html_document
---

This script must be run after 'OneSite_WatQualDataDownload_withQAQC' & 'OneSite_WatQuantityDownload_withRatingCurve' have been completed since it requires the annual QAQC files generated by boths scripts.


```{r setup, include=FALSE}
library(neonUtilities) ; library(dplyr) ; library(lubridate) ; library(EcoHydRology); library(tidyr)
library(xts)
options(stringsAsFactors=F) # character variables are not converted to factors

setwd("R:/EcosystemEcologyLab/MSAPLANKTONdataDirectory/DataInDevelopment/NEONData/ARIK/01_input")
```



```{r}
########need to readjust per each year###########################
  
  wat_quant = read.csv("wquant_data_QApass_2017.csv", header = T)
  
  wat_qual = read.csv("wq_data_QApass_2017.csv", header = T)

#################################################################

#Perform the baseflow separation using the EcoHydRology package for each water year. This will return a 2 column data frame with nrow = length of input streamflow data. The first column contains baseflow, while the second contains quickflow, both in the same units as the input.

  temp = BaseflowSeparation(wat_quant$withParaUncQMean, filter_parameter = 0.925, passes = 3)
    wat_quant$withParaUncQMean_base = temp[,1] #baseflow
      wat_quant$withParaUncQMean_Propbase = ((wat_quant$withParaUncQMean - wat_quant$withParaUncQMean_base)
                                                    /wat_quant$withParaUncQMean) #percent of instant flow classified as baseflow

#create subsets of water qual and quant datasets and merge them by datetime

wat_quant_subset = data.frame(matrix(ncol=0,nrow=nrow(wat_quant)))

wat_quant_subset$datetime = wat_quant$endDate
wat_quant_subset$meanFlow = wat_quant$withParaUncQMean
wat_quant_subset$sdFlow = wat_quant$withParaUncQStdDev
wat_quant_subset$propBaseFlow = wat_quant$withParaUncQMean_Propbase


wat_qual_subset = data.frame(matrix(ncol=0,nrow=nrow(wat_qual)))

wat_qual_subset$datetime = wat_qual$startDateTime
wat_qual_subset$chlorophyll = wat_qual$chlorophyll
wat_qual_subset$chl_unc = wat_qual$chlorophyllExpUncert
wat_qual_subset$turbidity = wat_qual$turbidity
wat_qual_subset$turb_unc = wat_qual$turbidityExpUncert

#both datasets are at 1-min interval, and not necessarily the same one, 
#aggregate each dataset to 5-minute intervals

wat_quant_subset$datetime = as.POSIXct(wat_quant_subset$datetime, format = "%Y-%m-%d %H:%M:%S")
wat_quant_subset = complete.cases(wat_quant_subset)

qxts <- xts(wat_quant_subset[,2:4], order.by=wat_quant_subset[,1])

period.apply(qxts, endpoints(qxts, "minutes", 15), mean)





class(wat_quant_subset$datetime)

 timeAverage(wat_quant_subset, avg.time = "5 min", fill = F)


 
 
 
 
 
 
 
 
 
 
 wat_quant_subset

wat_qual_subset = wat_qual_subset[!is.na(wat_qual_subset$chlorophyll),]

merged_data = left_join(merged_data,wat_qual,by="datetime")


```


