---
title: "One Site Water Quality Data Collection"
author: "Marc Peipoch"
date: "9/16/2022"
output: html_document
---

Stack downloaded data files into single .zip file
```{r setup, include=FALSE}
library(neonUtilities) ; library(dplyr) ; library(lubridate)
options(stringsAsFactors=F) # character variables are not converted to factors

site = "LECO"
  #Will do one site at a time




setwd(paste("R:/EcosystemEcologyLab/MSAPLANKTONdataDirectory/DataInDevelopment/NEONData/",site,"/01_input",sep=""))

dpID = "DP1.20166.001" #for periphyton, seston, and phytoplankton collection
#This data product contains the quality-controlled, native sampling resolution data from NEON's aquatic periphyton and phytoplankton collection and field metadata, as well as associated taxonomic, and enumeration data provided by contracted labs. Benthic and water column field samples are collected in wadeable streams, rivers, and lakes three times per year during the growing season. 

pack = "expanded"
  #Always expanded, includes quality metrics for all of the quality assessment and quality control analyses.
startdate = "2017-01" ; enddate = "2022-09"

memory.limit(size=50000) #to set a higher value fpr memory use limit

benthicColl <- loadByProduct(dpID, site, package=pack, startdate, enddate, check.size=FALSE) #returns a list with all data frames
list2env(benthicColl, .GlobalEnv) #extract each list object into the environment (don't do this if working with multiple sites)

#######save the files to SWRC server########
write.csv(alg_fieldData, 
          "alg_fieldData_Collection.csv", 
          row.names=F)

write.csv(alg_biomass, 
          "alg_biomass.csv", 
          row.names=F)

write.csv(alg_taxonomyProcessed, 
          "alg_taxonomyProcessed.csv", 
          row.names=F)

write.csv(alg_taxonomyRaw, 
          "alg_taxonomyRaw.csv", 
          row.names=F)

write.csv(alg_qualityCheck, 
          "alg_qualityCheck.csv", 
          row.names=F)

write.csv(alg_biovolumes, 
          "alg_biovolumes.csv", 
          row.names=F)
############################################################################################################################

dpID = "DP1.20163.001" #for Periphyton, seston, and phytoplankton chemical properties
#Carbon (C), nitrogen (N), phosphorus (P), isotopes, chlorophyll a, and pheophytin of periphyton and phytoplankton from benthic and water column samples in lakes, rivers, and wadeable streams


benthicProp <- loadByProduct(dpID, site, package=pack, startdate, enddate, check.size=FALSE) #returns a list with all data frames
list2env(benthicProp, .GlobalEnv) #extract each list object into the environment (don't do this if working with multiple sites)

#######save the files to SWRC server########
write.csv(alg_fieldData, 
          "alg_fieldData_Properties.csv", 
          row.names=F)

write.csv(alg_domainLabChemistry, 
          "alg_domainLabChemistry.csv", 
          row.names=F)

write.csv(alg_algaeExternalLabDataPerSample, 
          "alg_algaeExternalLabDataPerSample.csv", 
          row.names=F)

write.csv(alg_algaeExternalLabQA, 
          "alg_algaeExternalLabQA.csv", 
          row.names=F)

write.csv(asi_externalLabPOMSummaryData, 
          "asi_externalLabPOMSummaryData.csv", 
          row.names=F)

############################################################################################################################

```

Taxonomic Data________________________________________________________________________________________
Generate three species abundance matrices [division, family, and species], that are ready for analysis. That is, each phyla as a column, and each row represent one sample.date. In each matrix the first row will be sample date and can be removed prior to multivariate analysis 
```{r}
#The taxonomic count data with algalParameterUnit = cellsPerBottle are not corrected for preservative volume or benthic area. Data users will need to refer to the benthicArea presented in the alg_fieldData table and apply this correction to get the number of algal cells per stream, lake, or river bottom. All taxon records from a sample should be summed and divided by the benthicArea prior to reporting the total abundance per m2.


alg_fieldData = read.csv("alg_fieldData_Collection.csv")

#join biomass and fieldData tables
alg_fieldData_biomass = inner_join(alg_fieldData,alg_biomass, by="parentSampleID")

#join alg_fieldData_biomass and taxonomy data tables
alg_taxonomy_fieldbiomass = inner_join(alg_fieldData_biomass,alg_taxonomyProcessed, by="sampleID")

alg_taxonomy_fieldbiomass


alg_tax_division = alg_taxonomy_fieldbiomass %>%
  filter(algalParameter == "cell density") %>%
  select(collectDate, sampleID, algalParameterValue, division) %>%
  group_by(collectDate, sampleID, division) %>%
  summarise(total_fam = sum(algalParameterValue))
  



```
